FROM adoptopenjdk:8-jre-hotspot

WORKDIR /app

COPY ./MerchantMicroservice/target/merchant-microservice-thorntail.jar ./src/merchant-microservice.jar

CMD [ "java", \
      "-Xmx64m", \
      "-Djava.net.preferIPv4Stack=true", \
      "-Djava.net.preferIPv4Addresses=true", \
      "-jar", \
      "./src/merchant-microservice.jar" ]