FROM adoptopenjdk:8-jre-hotspot

WORKDIR /app

COPY ./TransactionMicroservice/target/transaction-microservice-thorntail.jar ./src/transaction-microservice.jar

CMD [ "java", \
      "-Xmx64m", \
      "-Djava.net.preferIPv4Stack=true", \
      "-Djava.net.preferIPv4Addresses=true", \
      "-jar", \
      "./src/transaction-microservice.jar" ]