FROM adoptopenjdk:8-jre-hotspot

WORKDIR /app

COPY ./TokenMicroservice/target/token-microservice-thorntail.jar ./src/token-microservice.jar

EXPOSE 8080

CMD [ "java", \
      "-Xmx64m", \
      "-Djava.net.preferIPv4Stack=true", \
      "-Djava.net.preferIPv4Addresses=true", \
      "-jar", \
      "./src/token-microservice.jar" ]

