FROM adoptopenjdk:8-jre-hotspot

WORKDIR /app

COPY ./CustomerMicroservice/target/customer-microservice-thorntail.jar ./src/customer-microservice.jar

CMD [ "java", \
      "-Xmx64m", \
      "-Djava.net.preferIPv4Stack=true", \
      "-Djava.net.preferIPv4Addresses=true", \
      "-jar", \
      "./src/customer-microservice.jar" ]